title: "Generatív AI és inverz módszerek a képszintézisben"
description: "Budapesti Műszaki és Gazdaságtudományi Egyetem"
baseurl: "/genai-inverse-graphics-bme-vik-iit"
url: "https://vaitkusm.github.io"

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - CLAUDE.md
  - syllabus.md
